name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag'
        required: false
        default: 'latest'

env:
  DOCKER_REGISTRY: testnetobscuronet.azurecr.io
  IMAGE_NAME: ten-contract-verification

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set image tag
      id: set-tag
      run: |
        TAG=${{ github.event.inputs.version }}
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.image_tag }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
